- ignore: { name: "Eta reduce" }
- ignore: { name: "Use newtype instead of data" }
- ignore: { name: "Use unless" }
- ignore: { name: "Use fmap" }
- ignore: { name: "Use tuple-section" }
- ignore: { name: "Use ++" }
- ignore: { name: "Use if" }
- ignore: { name: "Avoid lambda using `infix`" }
- ignore: { name: "Replace case with maybe" }
