resolver: lts-22.22
packages:
- autodocodec
- autodocodec-api-usage
- autodocodec-openapi3
- autodocodec-schema
- autodocodec-servant-multipart
- autodocodec-swagger2
- autodocodec-yaml
- autodocodec-nix

extra-deps:
- github: NorfairKing/validity
  commit: 6b06ec70bdd999f7450f88f4beea43f1607e3726
  subdirs:
    - validity
    - validity-aeson
    - validity-containers
    - validity-text
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text

- github: NorfairKing/safe-coloured-text
  commit: f1699005e9bf40a9676b89760aaf168d578c4419
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 6be618a53366d2453ba55da6cddc119d6d589916
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack

