resolver: lts-20.23
packages:
- autodocodec
- autodocodec-api-usage
- autodocodec-openapi3
- autodocodec-schema
- autodocodec-servant-multipart
- autodocodec-swagger2
- autodocodec-yaml
extra-deps:
- github: NorfairKing/validity
  commit: a251897dc1eb7e851fd4d3dbc6fa976d22388f27
  subdirs:
    - validity
    - validity-aeson
    - validity-containers
    - validity-text
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text

- github: NorfairKing/safe-coloured-text
  commit: f18578151d579c495eda46b8eeafcddb69adea07
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 6fc76ffc6f59c2b89f476e37a23f2547adf47ffd
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack

