resolver: lts-19.3
packages:
- autodocodec
- autodocodec-api-usage
- autodocodec-openapi3
- autodocodec-schema
- autodocodec-swagger2
- autodocodec-yaml
extra-deps:
- github: NorfairKing/validity
  commit: e042d0ba56436f8122a5e558d77ec6ff4160c0d9
  subdirs:
    - validity
    - validity-aeson
    - validity-containers
    - validity-text
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text

- github: NorfairKing/safe-coloured-text
  commit: 95860cbf6aa7c50d9c3702165bf6df25baf770b1
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: da5ff27751ced020900d88dca43bb20cd3dc3c87
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

nix:
  shell-file: shell.nix
