resolver: lts-19.6
packages:
- autodocodec
- autodocodec-api-usage
- autodocodec-openapi3
- autodocodec-schema
- autodocodec-swagger2
- autodocodec-yaml
extra-deps:
- github: NorfairKing/validity
  commit: d88be911a7e2a84f6c089e9269aaed8d10a74acd
  subdirs:
    - validity
    - validity-aeson
    - validity-containers
    - validity-text
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text

- github: NorfairKing/safe-coloured-text
  commit: d3fb43703a4b927362b7b83d8f2313173ad091a5
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 934bbf9cef011ea16ee0e8d8144e221d4a7cf2fb
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

nix:
  shell-file: shell.nix
