resolver: lts-24.16
packages:
- autodocodec
- autodocodec-api-usage
- autodocodec-exact
- autodocodec-nix
- autodocodec-openapi3
- autodocodec-schema
- autodocodec-servant-multipart
- autodocodec-swagger2
- autodocodec-yaml

extra-deps:
- github: NorfairKing/validity
  commit: 51b8843b9bd5228160b99f653d3271147245d689
  subdirs:
    - validity
    - validity-aeson
    - validity-containers
    - validity-dlist
    - validity-text
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-dlist
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text

- github: NorfairKing/opt-env-conf
  commit: f1a744f9497e0c0e017262dfa24b7aefe5250dd0
  subdirs:
    - opt-env-conf
    - opt-env-conf-test

- github: NorfairKing/safe-coloured-text
  commit: f1699005e9bf40a9676b89760aaf168d578c4419
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 710aa588759d3f9742216021e5b2c3cfcb919a9e
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack

