name: autodocodec-swagger2
version: 0.0.0.0
github: "NorfairKing/autodocodec"
license: MIT
license-file: LICENSE
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021 Tom Sydney Kerckhove"
synopsis: Swagger support for autodocodecs

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - autodocodec
  - swagger2
