name: autodocodec-yaml
version: 0.4.0.2
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021-2025 Tom Sydney Kerckhove"
synopsis: Autodocodec interpreters for yaml

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - autodocodec >= 0.5.0.0
  - autodocodec-schema >=0.2.0.1
  - bytestring
  - containers
  - path
  - path-io
  - safe-coloured-text >=0.3.0.1
  - scientific
  - text
  - vector
  - yaml
