name: autodocodec-yaml
version: 0.2.0.3
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021-2023 Tom Sydney Kerckhove"
synopsis: Autodocodec interpreters for yaml

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - autodocodec >= 0.2.0.0
  - autodocodec-schema >=0.1.0.0
  - bytestring
  - containers
  - path
  - path-io
  - safe-coloured-text >=0.2.0.0
  - scientific
  - text
  - vector
  - yaml
