name: autodocodec-yaml
version: 0.1.0.1
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021 Tom Sydney Kerckhove"
synopsis: Autodocodec interpreters for yaml

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-compat
  - autodocodec
  - autodocodec-schema >=0.1.0.0
  - bytestring
  - containers
  - path
  - path-io
  - safe-coloured-text
  - scientific
  - text
  - unordered-containers
  - vector
  - yaml
