name: autodocodec-exact
version: 0.0.0.2
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2025 Tom Sydney Kerckhove"
synopsis: Exact decoder for autodocodec

extra-source-files:
- LICENSE
- CHANGELOG.md

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Widentities
- -Wredundant-constraints
- -Wcpp-undef

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec >= 0.6.0.0
  - bytestring
  - containers
  - mtl
  - pretty-show
  - scientific
  - scientific
  - text
  - unordered-containers
  - vector
