name: autodocodec-api-usage
version: 0.0.0.0
github: "NorfairKing/autodocodec"
license: MIT
license-file: LICENSE
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021 Tom Sydney Kerckhove"
synopsis: Autodocodec api usage tests

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - aeson
  - autodocodec
  - autodocodec-aeson
  - autodocodec-yaml
  - bytestring
  - genvalidity
  - genvalidity-aeson
  - genvalidity-scientific
  - genvalidity-text
  - scientific
  - text


tests:
  autodocodec-api-usage-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - autodocodec-aeson
    - autodocodec-api-usage
    - autodocodec-yaml
    - bytestring
    - containers
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - safe-coloured-text
    - scientific
    - sydtest
    - sydtest-aeson
    - text
