name: autodocodec-api-usage
version: 0.0.0.0
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021-2022 Tom Sydney Kerckhove"
synopsis: Autodocodec api usage tests

extra-source-files:
- LICENSE
- test_resources/**/*

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - aeson
  - autodocodec >=0.2.0.0
  - autodocodec-openapi3
  - autodocodec-schema
  - autodocodec-servant-multipart
  - autodocodec-swagger2
  - autodocodec-yaml
  - bytestring
  - deepseq
  - genvalidity
  - genvalidity-aeson
  - genvalidity-scientific
  - genvalidity-text
  - openapi3
  - scientific
  - servant-multipart
  - servant-multipart-api
  - swagger2
  - text
  - unordered-containers
  - yaml


tests:
  autodocodec-api-usage-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - autodocodec-api-usage
    - autodocodec-openapi3
    - autodocodec-schema
    - autodocodec-servant-multipart
    - autodocodec-swagger2
    - autodocodec-yaml
    - bytestring
    - containers
    - genvalidity
    - autodocodec-nix
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - genvalidity-time
    - openapi3
    - pretty-show
    - safe-coloured-text
    - scientific
    - servant-multipart-api
    - swagger2
    - sydtest
    - sydtest-aeson
    - text
    - time
    - yaml
    - vector

benchmarks:
  autodocodec-api-usage-bench:
    main: Main.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - autodocodec-api-usage
    - bytestring
    - containers
    - criterion
    - deepseq
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - scientific
    - text
    - time
    - vector
