name: autodocodec-aeson
version: 0.0.0.0
github: "NorfairKing/autodocodec"
license: MIT
license-file: LICENSE
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021 Tom Sydney Kerckhove"
synopsis: Self-documenting encoder and decoder for aeson

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - autodocodec
  - bytestring
  - containers
  - mtl
  - scientific
  - text
  - unordered-containers
  - validity
  - validity-aeson
  - validity-containers
  - validity-text

tests:
  autodocodec-aeson-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - aeson
    - autodocodec
    - autodocodec-aeson
    - bytestring
    - containers
    - genvalidity
    - genvalidity-aeson
    - genvalidity-containers
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-text
    - scientific
    - sydtest
    - sydtest-aeson
    - text
