name: autodocodec-http-api-data
version: 0.0.0.0
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2026 Tom Sydney Kerckhove"
synopsis: Autodocodec interpreters for http-api-data

extra-source-files:
- LICENSE
- CHANGELOG.md

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Widentities
- -Wredundant-constraints
- -Wcpp-undef

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - autodocodec >=0.6.0.0
  - bytestring
  - http-api-data
  - text
  - unordered-containers
  - vector
