name: autodocodec
version: 0.4.2.1
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021-2024 Tom Sydney Kerckhove"
synopsis: Self-documenting encoder and decoder

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - containers
  - dlist
  - hashable
  - mtl
  - scientific
  - scientific
  - text
  - time
  - unordered-containers
  - validity
  - validity-scientific
  - vector

tests:
  autodocodec-doctest:
    main: DocTest.hs
    source-dirs: doctest/
    ghc-options:
    - -main-is DocTest
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - doctest
