name: autodocodec
version: 0.2.0.5
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021-2023 Tom Sydney Kerckhove"
synopsis: Self-documenting encoder and decoder

extra-source-files:
- LICENSE
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - bytestring
  - containers
  - hashable
  - mtl
  - scientific
  - text
  - time
  - unordered-containers
  - validity
  - validity-scientific
  - vector

tests:
  autodocodec-doctest:
    # Turn off doctests until this issue is fixed:
    # https://github.com/sol/doctest/issues/327
    when:
      - condition: impl(GHC < 9.0)
        then:
          buildable: true
        else:
          buildable: false

    main: DocTest.hs
    source-dirs: doctest/
    ghc-options:
    - -main-is DocTest
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - doctest

