name: autodocodec-openapi3
version: 0.3.0.2
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021-2022 Tom Sydney Kerckhove"
synopsis: Autodocodec interpreters for openapi3

extra-source-files:
- LICENSE
- CHANGELOG.md

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Widentities
- -Wredundant-constraints
- -Wcpp-undef

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - autodocodec >= 0.6.0.0
  - unordered-containers
  - insert-ordered-containers
  - lens
  - mtl
  - openapi3
  - scientific
  - text
