name: autodocodec-schema
version: 0.2.0.2
github: "NorfairKing/autodocodec"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "2021-2025 Tom Sydney Kerckhove"
synopsis: Autodocodec interpreters for JSON Schema

extra-source-files:
- LICENSE
- CHANGELOG.md

ghc-options:
- -Wall
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wpartial-fields
- -Widentities
- -Wredundant-constraints
- -Wcpp-undef

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - aeson
  - autodocodec >=0.6.0.0
  - containers
  - mtl
  - scientific
  - text
  - unordered-containers
  - validity
  - validity-aeson
  - validity-containers
  - validity-text
