name: "Nix Build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v14.1
    - name: free disk space
      run: |
        sudo rm -rf /opt
    - uses: cachix/cachix-action@v10
      with:
        name: autodocodec
        extraPullNames: validity,safe-coloured-text,sydtest
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build default.nix
    - run: nix-build ci.nix
